micronaut:
  application:
    name: sensor-firmware-updater
  server:
    port: 80
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  prometheus:
    sensitive: false

firmware:
  devices:
    ONE:
      version-to-path:
        "0.8.4": "firmwares/ONE/0.8.4.bin"
