micronaut:
  application:
    name: sensor-firmware-updater
  server:
    port: 80
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  prometheus:
    sensitive: false

firmware:
  devices:
    - id: "ONE"
      versions:
        - version: "0.8.4"
          path: "firmwares/ONE/0.8.4.bin"
